api_keys:
  gpt-4.1: "YOUR_KEY"
oauth:
  client_id: "GOOGLE_CLIENT_ID"
  client_secret: "GOOGLE_CLIENT_SECRET"
  redirect_uri: "https://uv3.duckdns.org:1944/oauth2callback"
tls:
  certfile: "/path/to/cert.pem"
  keyfile: "/path/to/key.pem"
marketplace:
  enabled: true
  endpoint: "https://api.github.com/marketplace/models"
default_model: "gpt-4.1"
models:
  gpt-4.1: {}
  gpt-4.1-mini: {}
  gpt-4.1-nano: {}
  codestral-25.01: {}
  grok-3: {}
  phi-4-reasoning: {}
  deepseek-r1: {}
  llama-3.2-11b-vision-instruct: {}
